"""Club jersey art for the squad page.

Each Premiership club has its own kit SVG, generated by
tools/generate_jerseys.py into api/static/img/jerseys/<CODE>.svg. The squad page
builds the URL straight from a player's `real_team`, so the filenames ARE the
join key — a club whose code drifts from the fixtures feed silently loses its
jersey and falls back to a flat colour.

The geometry assertions matter as much as the file list: the art is sized to drop
into the squad token's 4:3 box in place of a CSS mask, and the pitch layout is
tuned to that footprint (the S/B/O status dot hangs off the jersey's left edge,
the hem sits on the token's bottom edge). A viewBox that isn't 4:3 would either
distort the kit — an elliptical club badge — or shift it away from those offsets.
"""

import os
import xml.etree.ElementTree as ET

import pytest

from api import prem_fixtures
from api.index import JERSEY_DIR, _jersey_codes

# The squad token is 80x60 / 64x48 / 44x33 — always 4:3 (see .fp-shirt in
# api/static/css/squad.css).
TOKEN_ASPECT = 4 / 3
EXPECTED_VIEWBOX = (-6.0, 16.0, 112.0, 84.0)
# The shirt path's own extent on the generator's canvas.
SHIRT_X = (6.0, 94.0)
SHIRT_Y = (16.0, 100.0)


def _svg(code):
    return os.path.join(JERSEY_DIR, f'{code}.svg')


def _codes():
    codes = sorted(_jersey_codes())
    if not codes:
        pytest.skip('no jersey art generated — run tools/generate_jerseys.py')
    return codes


def test_every_club_in_the_fixtures_feed_has_a_jersey():
    """Promotion, relegation or a rebrand must not leave a club kitless."""
    missing = sorted(set(prem_fixtures.clubs()) - _jersey_codes())

    assert not missing, f'no jersey art for {missing} (run tools/generate_jerseys.py)'


def test_no_jersey_art_for_a_club_that_does_not_exist():
    """A stale file is a rename that didn't finish — the old code would never be
    requested, and the new one would 404 into an empty token."""
    orphans = sorted(_jersey_codes() - set(prem_fixtures.clubs()))

    assert not orphans, f'jersey art for unknown clubs: {orphans}'


def test_filenames_are_canonical_club_codes():
    """The filename is the lookup key, so it has to be what resolve_team returns."""
    for code in _codes():
        assert prem_fixtures.resolve_team(code) == code


@pytest.mark.parametrize('code', _codes())
def test_jersey_is_well_formed_svg(code):
    root = ET.parse(_svg(code)).getroot()

    assert root.tag == '{http://www.w3.org/2000/svg}svg'
    assert root.get('viewBox')


@pytest.mark.parametrize('code', _codes())
def test_viewbox_matches_the_token_box(code):
    """4:3, so the art scales uniformly into the token and the badge stays round."""
    vb = tuple(float(v) for v in ET.parse(_svg(code)).getroot().get('viewBox').split())

    assert vb == EXPECTED_VIEWBOX
    _, _, w, h = vb
    assert w / h == pytest.approx(TOKEN_ASPECT)


def test_art_lands_where_the_css_mask_used_to():
    """The pitch offsets assume the old silhouette's footprint: x 10%..90% of the
    token, hem on the bottom edge. Keep the art within ~1pp of that."""
    vx, vy, vw, vh = EXPECTED_VIEWBOX

    left = (SHIRT_X[0] - vx) / vw * 100
    right = (SHIRT_X[1] - vx) / vw * 100
    top = (SHIRT_Y[0] - vy) / vh * 100
    bottom = (SHIRT_Y[1] - vy) / vh * 100

    assert left == pytest.approx(10, abs=1)      # status dot hangs at left: 10%
    assert right == pytest.approx(90, abs=1)
    assert top == pytest.approx(0, abs=1)
    assert bottom == pytest.approx(100, abs=1)   # hem at bottom: ~0%


def test_the_jersey_number_has_room_below_the_club_badge():
    """The number is seated in the lower torso via `align-content: end`. If the
    badge grew or moved down, the two would collide."""
    _, vy, _, vh = EXPECTED_VIEWBOX
    badge_cy, badge_r = 51.0, 12.0

    badge_bottom = (badge_cy + badge_r - vy) / vh * 100
    hem = (SHIRT_Y[1] - vy) / vh * 100

    assert hem - badge_bottom >= 25, 'not enough clear torso below the club badge'


@pytest.mark.parametrize('code', _codes())
def test_clip_path_id_is_unique_per_club(code):
    """The contact sheet inlines all ten in one document; a shared id would make
    every shirt clip to whichever came first."""
    root = ET.parse(_svg(code)).getroot()
    clips = root.iter('{http://www.w3.org/2000/svg}clipPath')
    ids = [c.get('id') for c in clips]

    assert ids == [f'jersey-{code}']


def test_a_league_without_club_colours_gets_no_jerseys(monkeypatch):
    """Super Rugby has no scraped club list and no art, so its tokens must keep
    the flat silhouette — never inherit a Premiership kit off a code collision."""
    from api import index as idx

    monkeypatch.setattr(idx, '_club_colours', lambda conn, league_id: {})

    assert idx._club_jerseys(None, 1) == []


def test_only_clubs_in_this_league_are_offered(monkeypatch):
    """The list is an intersection: art on disk AND a club in this league."""
    from api import index as idx

    monkeypatch.setattr(idx, '_club_colours',
                        lambda conn, league_id: {'BAT': '#000', 'XXX': '#fff'})

    assert idx._club_jerseys(None, 1) == ['BAT']


@pytest.mark.parametrize('code', _codes())
def test_jersey_carries_the_club_badge_text(code):
    """The badge is the club code — the detail that makes a kit identifiable at
    token size, and what was explicitly asked to be kept."""
    texts = [t.text for t in ET.parse(_svg(code)).getroot()
             .iter('{http://www.w3.org/2000/svg}text')]

    assert code in texts
